//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using DomainModel;

namespace DataMapper.EntityFrameworkDataMapper
{
    public partial class BiddingDataModelContainer : ObjectContext
    {
        public const string ConnectionString = "name=BiddingDataModelContainer";
        public const string ContainerName = "BiddingDataModelContainer";
    
        #region Constructors
    
        public BiddingDataModelContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public BiddingDataModelContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public BiddingDataModelContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Product> Products
        {
            get { return _products  ?? (_products = CreateObjectSet<Product>("Products")); }
        }
        private ObjectSet<Product> _products;
    
        public ObjectSet<Category> Categories
        {
            get { return _categories  ?? (_categories = CreateObjectSet<Category>("Categories")); }
        }
        private ObjectSet<Category> _categories;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<Bid> Bids
        {
            get { return _bids  ?? (_bids = CreateObjectSet<Bid>("Bids")); }
        }
        private ObjectSet<Bid> _bids;
    
        public ObjectSet<UserRating> UserRatings
        {
            get { return _userRatings  ?? (_userRatings = CreateObjectSet<UserRating>("UserRatings")); }
        }
        private ObjectSet<UserRating> _userRatings;
    
        public ObjectSet<Role> Roles
        {
            get { return _roles  ?? (_roles = CreateObjectSet<Role>("Roles")); }
        }
        private ObjectSet<Role> _roles;

        #endregion

    }
}
