//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Bids = new HashSet<Bid>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public System.DateTime BidStartDate { get; set; }
        public System.DateTime BidEndDate { get; set; }
        public decimal StartingPrice { get; set; }
        public string BidCurrency { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Bid> Bids { get; set; }
    }
}
